version: "3.8"

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: always
    ports:
      - "6379:6379"    # Puerto para Redis (acceso a la base de datos)
      - "9091:8001"    # Puerto para RedisInsight (visualización de datos)
    # environment:
    #   - REDIS_ARGS=--requirepass mypassword  # (Opcional) Configuración de password para mayor seguridad

# tengo que unir este docker-compose con el docker-compose de angular, springboot y mysql
