apiVersion: v1
kind: Service
metadata:
  name: angular-service        # Nombre del servicio.
spec:
  selector:
    app: angular               # Selector que conecta el servicio al Deployment Angular.
  ports:
    - protocol: TCP
      port: 4200                 # Puerto externo visible al usuario.
      targetPort: 4200           # Puerto dentro del contenedor Angular.
      nodePort: 30001          # Puerto accesible desde el exterior del nodo.
  type: NodePort
