apiVersion: v1
kind: Service
metadata:
  name: prometheus                 # Nombre del Servicio, debe coincidir con lo que vas a usar en `kubectl port-forward`
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus                # Este selector asegura que el servicio se asocia al Pod de Prometheus.
  ports:
  - protocol: TCP
    port: 9090                     # Puerto expuesto por el Servicio.
    targetPort: 9090               # Puerto al que apunta en el contenedor de Prometheus.
  type: ClusterIP                  # Tipo de Servicio (opcional, por defecto es ClusterIP).
