apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379          # Puerto del servicio
      targetPort: 6379    # Puerto del contenedor Redis
  type: ClusterIP         # Tipo de servicio para comunicación interna
